<?php
/**
 * @OA\Get(
 *     path="/api/backAdmin/user",
 *     summary="获取用户信息",
 *     description="获取用户信息",
 *     tags={"管理后台"},
 *     @OA\Parameter(ref="#/components/parameters/bear_token"),
 *     @OA\Parameter(name="userId",
 *          in="query",
 *          required=true,
 *          description = "用户id",
 *          @OA\Schema(type="integer")),
 *     @OA\Response(
 *          response=200,
 *          description="返回更新结果",
 *          @OA\JsonContent(
 *              allOf={
 *                  @OA\Schema(ref="#/components/schemas/dzq_layout"),
 *                  @OA\Schema(@OA\Property(property="Data",type="object",
 *                      @OA\Property(property="id",type="integer",description = "用户id"),
 *                      @OA\Property(property="username",type="integer",description = "用户名"),
 *                      @OA\Property(property="mobile",type="integer",description = "手机号（脱敏）"),
 *                      @OA\Property(property="isReal",type="integer",description = "是否实名"),
 *                      @OA\Property(property="avatarUrl",type="integer",description = "头像地址"),
 *                      @OA\Property(property="threadCount",type="integer",description = "主题数"),
 *                      @OA\Property(property="followCount",type="integer",description = "关注数"),
 *                      @OA\Property(property="fansCount",type="integer",description = "粉丝数"),
 *                      @OA\Property(property="likedCount",type="integer",description = "主题点赞数"),
 *                      @OA\Property(property="questionCount",type="integer",description = "提问数"),
 *                      @OA\Property(property="signature",type="integer",description = "签名"),
 *                      @OA\Property(property="usernameBout",type="integer",description = "用户名修改次数"),
 *                      @OA\Property(property="follow",type="integer",description = "关注状态：null 未登录/登陆用户与查询用户相同0 未关注1 已关注2 互相关注"),
 *                      @OA\Property(property="status",type="integer",description = "状态"),
 *                      @OA\Property(property="loginAt",type="string",format="datetime",default="2021-01-02 02:22:22",description = "登录时间"),
 *                      @OA\Property(property="joinedAt",type="string",format="datetime",default="2021-01-02 02:22:22",description = "加入时间"),
 *                      @OA\Property(property="expiredAt",type="string",format="datetime",default="2021-01-02 02:22:22",description = "到期时间"),
 *                      @OA\Property(property="createdAt",type="string",format="datetime",default="2021-01-02 02:22:22",description = "创建时间"),
 *                      @OA\Property(property="updatedAt",type="string",format="datetime",default="2021-01-02 02:22:22",description = "修改时间"),
 *                      @OA\Property(property="canEdit",type="boolean",description = "是否可以编辑"),
 *                      @OA\Property(property="canDelete",type="boolean",description = "是否可以删除"),
 *                      @OA\Property(property="canWalletPay",type="boolean",description = "是否可以使用钱包支付"),
 *                      @OA\Property(property="showGroups",type="boolean",description = "是否显示群组"),
 *                      @OA\Property(property="registerReason",type="string",description = "注册理由"),
 *                      @OA\Property(property="banReason",type="string",description = "禁用理由"),
 *                      @OA\Property(property="denyStatus",type="boolean",description = "拒绝状态"),
 *                      @OA\Property(property="canBeAsked",type="boolean",description = "可以被提问"),
 *                      @OA\Property(property="canEditUsername",type="boolean",description = "是否可编辑名称"),
 *                      @OA\Property(property="mpOpenid",type="string",description = "公众号openid"),
 *                      @OA\Property(property="devOpenid",type="string",description = "开放平台openid"),
 *                      @OA\Property(property="minOpenid",type="string",description = "小程序openid"),
 *                      @OA\Property(property="nickname",type="string",description = "微信昵称"),
 *                      @OA\Property(property="unionid",type="string",description = "只有在用户将公众号绑定到微信开放平台帐号后，才会出现该字段"),
 *                      @OA\Property(property="backgroundUrl",type="string",description = "背景图地址"),
 *                      @OA\Property(property="paid",type="boolean",description = "是否付费"),
 *                      @OA\Property(property="payTime",type="string",format="datetime",default="2021-01-02 02:22:22",description = "付费时间"),
 *                      @OA\Property(property="unreadNotifications",type="boolean",description = "未读消息数"),
 *                      @OA\Property(property="typeUnreadNotifications",type="object",description = "未读消息类型",
 *                          @OA\Property(property="liked",type="integer",description = "点赞数"),
 *                          @OA\Property(property="related",type="integer",description = "@我"),
 *                          @OA\Property(property="replied",type="integer",description = "回复"),
 *                          @OA\Property(property="rewarded",type="integer",description = "财务通知"),
 *                          @OA\Property(property="questioned",type="integer",description = "问答"),
 *                          @OA\Property(property="system",type="integer",description = "系统通知"),
 *                          @OA\Property(property="receiveredpacket",type="integer",description = "领取红包"),
 *                      ),
 *                      @OA\Property(property="isDeny",type="boolean",description = "是否屏蔽"),
 *                      @OA\Property(property="group",type="object",description = "用户组信息",
 *                          @OA\Property(property="groupId",type="integer",description = "用户组id"),
 *                          @OA\Property(property="groupName",type="string",description = "用户组名"),
 *                      ),
 *                      @OA\Property(property="hasPassword",type="boolean",description = "是否设置密码"),
 *                      @OA\Property(property="isBindWechat",type="boolean",description = "是否绑定微信"),
 *                      @OA\Property(property="wxNickname",type="string",description = "微信昵称"),
 *                      @OA\Property(property="wxHeadImgUrl",type="string",description = "微信头像"),
 *                      @OA\Property(property="isRenew",type="boolean",description = "是否续过费")
 *
 *                  ))
 *          }))
 * )
 */
